More sound organization.

diff --git a/zsh/dotZshenv b/zsh/dotZshenv
--- a/zsh/dotZshenv
+++ b/zsh/dotZshenv
@@ -1,1 +1,54 @@
+_CONFIG_HOST_SYSTEM=`uname`
+
+# Highlight
 export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
+source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+
+# History
+export HISTSIZE=50000
+export SAVEHIST=50000
+export HISTCONTROL=ignoredups
+
+# Editors
+export SVN_EDITOR="vim"
+export EDITOR="vim"
+export GIT_EDITOR="vim"
+
+# Force Language
+export LC_ALL=en_US.UTF-8
+export LC=en_US.UTF-8
+
+# Term
+export TERM="screen-256color"
+
+# VirtualEnv
+export WORKON_HOME=$HOME/.virtualenvs
+export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
+export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
+export PIP_VIRTUALENV_BASE=$WORKON_HOME
+export PIP_RESPECT_VIRTUALENV=true
+
+if [[ -r /usr/local/bin/virtualenvwrapper.sh ]]; then
+    source /usr/local/bin/virtualenvwrapper.sh
+else
+    echo "WARNING: Can't find virtualenvwrapper.sh"
+fi
+
+# rbenv
+export PATH="$HOME/.rbenv/bin:$PATH"
+eval "$(rbenv init -)"
+
+# Postgres93
+PATH="/Applications/Postgres93.app/Contents/MacOS/bin:$PATH:$PATH"
+
+# Fix zsh git slowness. Very Useful.
+# http://marc-abramowitz.com/archives/2012/04/10/fix-for-oh-my-zsh-git-svn-prompt-slowness/
+function git_prompt_info() {
+  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
+  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
+}
+
+# Keep
+function commands() {
+  history | sed "s/^[0-9 ]*//" | sed "s/ *| */\n/g" | awk '{print $1}' | sort | uniq -c | sort -rn | head -n 100 > ~/commands.txt && cat ~/commands.txt
+}
